# Basic TOML configuration for Alacritty
[general]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.7
dimensions.columns = 170
dimensions.lines = 40

[font]
normal.family = "Ubuntu Mono"
size = 9

[cursor]
style.shape = "Beam"
style.blinking = "Always"

[colors.cursor]
# Set the cursor color to green
cursor = "#00FF00"  # Green color for the cursor

[colors.selection]
text = "0xffffff"    # white text
background = "0x476D7B"  # Light blueish highlight (adjust as needed)

[colors.primary]
background = "#000000"  # Dark background (adjust as needed)
foreground = "#FFFFFF"  # Light text


# Normal Colours
[colors.normal]
black   = '#1a1a1a'
red     = '#f4005f' #orangeish typa red
green   = '#00FC26'
yellow  = '#fa8419'
blue    = '#878DEB'
magenta = '#f4005f'
cyan    = '#878DEB'
white   = '#c4c5b5'

# Bright Colours
[colors.bright]
black   = '#625e4c'
red     = '#D84315' #orangish typa red
green   = '#00FC26'
yellow  = '#e0d561'
blue    = '#878DEB'
magenta = '#f4005f'
cyan    = '#878DEB'
white   = '#f6f6ef'
